# This is a basic workflow to help you get started with Actions

name: healthchecks.io pings

on:
  workflow_dispatch:
  schedule:
    - cron: '3 * * * *'

jobs:
  healthchecks:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm code@solvaholic.com exists
        env:
          HC_URL: ${{ secrets.HC_URL_CODE_AT_SOLVAHOLIC_DOT_COM }}
        run: |
          _mailhost="$(dig mx solvaholic.com +short | awk 'NR==1 {print$2}')"
          _attempt=1
          _result=1
          for _attempt in {1..3}; do
            echo "EHLO solvaholic.com
            MAIL FROM: test@solvaholic.com
            RCPT TO: code@solvaholic.com
            QUIT" | nc $_mailhost 25 | grep -qsF "250 2.1.5 Ok"
            _result=$?
            [ $_result -eq 0 ] && break
          done
          if [ $_result -eq 0 ]; then
            curl -fsS -m 10 --retry 5 -o /dev/null "$HC_URL"
          fi
